config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'

  namespace :admin do
    resources :products
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      delete :clear_cart
      post   :checkout
    end
  end

  resources :cart_items
  resources :orders

  namespace :account do
    resources :orders
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items, source: :product

  def add_product_to_cart(product)
    cb = cart_items.build
    cb.product = product
    cb.quantity = 1
    cb.save
  end

  def total_price
    sum = 0
    cart_items.each do |cart_item|
      if cart_item.product.price.present?
        sum += cart_item.quantity * cart_item.product.price
      end
    end
    sum
  end

  def clear!
    cart_items.destroy_all
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :product_lists

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_address, presence: true

  before_create :generate_token
  
  def generate_token
    self.token = SecureRandom.uuid
  end
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/product_list.rb
class ProductList < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    is_admin
  end

  has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def admin_required
    if !current_user.admin?
      redirect_to '/', alert: "You're not admin!"
    end
  end

  helper_method :current_cart

  def current_cart
    @current_cart ||= find_cart
  end

  private

  def find_cart
    cart = Cart.find_by(id: session[:cart_id])
    if cart.blank?
      cart = Cart.create
    end
    session[:cart_id] = cart.id
    return cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_user!

  def update
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    if @cart_item.product.quantity >= cart_item_params[:quantity].to_i
      @cart_item.update(cart_item_params)
      flash[:notice] = "You've successfully change the number!"
    else
      flash[:notice] = "The quantity is not enough to add to cart"
    end
    redirect_to :back
  end

  def destroy
    @cart = current_cart
    @cart_item = @cart.cart_items.find_by(product_id: params[:id])
    @cart_item.destroy
    @product = @cart_item.product
    redirect_to :back
    flash[:alert] = "You've deleted the #{@product.title} from the cart!"
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:quantity)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def clear_cart
    current_cart.clear!
    redirect_to :back
    flash[:warning] = "You've clear the cart!"
  end

  def checkout
    @order = Order.new
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def show
    @order = Order.find_by_token(params[:id])
    @product_lists = @order.product_lists
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total = current_cart.total_price

    if @order.save
      current_cart.cart_items.each do |cart_item|
        product_list = ProductList.new
        product_list.order = @order
        product_list.product_name = cart_item.product.title
        product_list.product_price = cart_item.product.price
        product_list.quantity = cart_item.quantity
        product_list.save
      end

      redirect_to order_path(@order.token)
    else
      render 'carts/checkout'
    end
  end

  private

  def order_params
    params.require(:order).permit(:billing_name, :billing_address, :shipping_name, :shipping_address)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if !current_cart.products.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "Successfully add #{@product.title} to cart!"
    else
      flash[:warning] = "You've already add it to cart!"
    end
    redirect_to :back
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # flash[:notice] = "Good Morning!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="footer">
    <p>Copyright ©2017 JDStore
        <br>Design by
        <a href="https://github.com/yammmy/supermall" target="_blank">yammy</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" style="margin-left: 20px;" href="/">Beautys</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                <%= link_to("Products", products_path) %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to carts_path do %>
                  Shopping Cart <i class="fa fa-shopping-cart"></i> ( <%= current_cart.products.count%> )
                <% end %>
              </li>
              <% if !current_user %>
                 <button class="button">
                   <%= link_to('<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path) %>
                 </button>
                 <button class="button">
                   <%= link_to('<span class="glyphicon glyphicon-user"></span> Sign up'.html_safe, new_user_registration_path) %>
                 </button>
               <% else %>
                 <li class="dropdown">
                   <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       <i class="fa fa-user"></i> <%= current_user.name %>
                       <b class="caret"></b>
                   </a>
                   <ul class="dropdown-menu">
                       <% if current_user.admin? %>
                          <li>
                            <%= link_to(content_tag(:i, "Admin Panel", class: "fa fa-user-circle-o"), admin_products_path ) %>
                          </li>
                        <% end %>
                        <li>
                           <%= link_to(content_tag(:i, "My Orders", class: "fa fa-chevron-circle-down"), account_orders_path )%>
                        </li>
                       <li>
                          <%= link_to(content_tag(:i, "Logout", class: "fa fa-sign-out"), destroy_user_session_path, method: :delete)%>
                       </li>
                   </ul>
                 </li>
               <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Beautier backend</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row">
    <%= render "common/navbar" %>
  </div>
  <div class="container-fluid">
    <div class="col-md-2">
      <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">
        <li> <%= link_to("Products", admin_products_path) %> </li>
      </ul>
    </div>
    <div class="col-md-10">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beautier</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="row">
      <%= render "common/navbar" %>
    </div>
    <div class="container-fluid">
      <%= render "common/flashes" %>
      <%= yield %>
    </div>
    <div class="row">
      <%= render "common/footer" %>
    </div>
  </body>
</html>